auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9096

common:
  path_prefix: /loki
  storage:
    filesystem:
      chunks_directory: /loki/chunks
      rules_directory: /loki/rules
  replication_factor: 1
  ring:
    kvstore:
      store: inmemory

schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

storage_config:
  boltdb_shipper:
    active_index_directory: /loki/boltdb-shipper-active
    cache_location: /loki/boltdb-shipper-cache
    shared_store: filesystem

compactor:
  working_directory: /loki/compactor
  shared_store: filesystem

limits_config:
  # Optimized for local development
  ingestion_rate_mb: 10  # Reduced from 20MB for local
  ingestion_burst_size_mb: 10
  per_stream_rate_limit: 5MB  # Reduced from 10MB for local
  per_stream_rate_limit_burst: 5MB
  max_query_length: 721h  # 30 days
  max_query_parallelism: 16
  max_cache_freshness_per_query: 1m
  max_entries_limit_per_query: 5000
  max_global_streams_per_user: 1000
  max_line_size: 2MB
  max_query_series: 500
  max_streams_per_user: 1000
  max_streams_matchers_per_query: 1000
  max_concurrent_tail_requests: 10
  max_entries_limit_per_query: 5000
  max_global_streams_per_user: 1000
  max_line_size: 2MB
  max_query_series: 500
  max_streams_per_user: 1000
  max_streams_matchers_per_query: 1000
  max_concurrent_tail_requests: 10

# Local development optimizations
query_range:
  results_cache:
    cache:
      embedded_cache:
        enabled: true
        max_size_mb: 100
        validity: 24h

frontend:
  compress_responses: true
  log_queries_longer_than: 5s
  downstream_url: http://localhost:3100 