server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml  # Tracks log file positions

clients:
  - url: http://loki:3100/loki/api/v1/push
    backoff_config:
      min_period: 1s
      max_period: 5s
      max_retries: 5
    timeout: 10s

scrape_configs:
  - job_name: system
    static_configs:
      - targets: [localhost]
        labels:
          job: varlogs
          __path__: /var/log/*.log  # System logs
          host: ${HOSTNAME}

  - job_name: docker
    pipeline_stages:
      - docker: { }  # Parse Docker metadata
      - json:
          expressions:
            stream: stream
            log: log
            time: time
            attrs: attrs
      - labels:
          stream:
          container_name:
          image:
    static_configs:
      - targets: [ localhost ]
        labels:
          job: docker
          __path__: /var/lib/docker/containers/*/*.log
          host: ${HOSTNAME}

  - job_name: review-applications
    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            level: level
            logger: logger
            message: message
            thread: thread
      - labels:
          level:
          logger:
          application:
      - timestamp:
          source: timestamp
          format: RFC3339Nano
    static_configs:
      - targets: [localhost]
        labels:
          job: review-apps
          __path__: /logs/*.log  # Your custom app logs from volume mount
          host: ${HOSTNAME}
          application: review-system