server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml  # Tracks log file positions

clients:
  - url: http://loki:3100/loki/api/v1/push
    backoff_config:
      min_period: 1s
      max_period: 5s
      max_retries: 5
    timeout: 10s

scrape_configs:
  - job_name: system
    static_configs:
      - targets: [localhost]
        labels:
          job: varlogs
          __path__: /var/log/*.log  # System logs
          host: ${HOSTNAME}

  - job_name: docker
    pipeline_stages:
      - docker: { }  # Parse Docker metadata
    static_configs:
      - targets: [ localhost ]
        labels:
          job: docker
          __path__: /var/lib/docker/containers/*/*.log
          host: ${HOSTNAME}
          container_name: "{{.Name}}"  # Adds container name as label

  - job_name: applications
    static_configs:
      - targets: [localhost]
        labels:
          job: apps
          __path__: /logs/*.log  # Your custom app logs
          host: ${HOSTNAME}