server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: review-applications
    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            level: level
            logger: logger
            message: message
            thread: thread
      - labels:
          level:
          logger:
          application:
      - timestamp:
          source: timestamp
          format: RFC3339Nano

    relabel_configs:
      - source_labels: [__path__]
        regex: .*/([^/]+)\.log
        target_label: __tmp_filename
      - source_labels: [__tmp_filename]
        regex: (.*?)(-error)?$
        target_label: component
        replacement: $1
      - source_labels: [__tmp_filename]
        regex: .*?-error$
        target_label: error
        replacement: "true"
      - source_labels: [error]
        regex: ""
        target_label: error
        replacement: "false"

    static_configs:
      - targets: [localhost]
        labels:
          job: review-apps
          __path__: /logs/*.log
          host: ${HOSTNAME}
          application: review-system
