server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: review-apps
    static_configs:
      - targets:
          - localhost
        labels:
          job: review-apps
          application: review-system
          __path__: /logs/*.log

    pipeline_stages:
      - regex:
          expression: '/logs/(?P<filename>[^/]+\.log)'
      - replace:
          expression: '(?P<component>[^.]+)(-[^.]*)?\.log'
          replace: '$1'
          source: filename
      - regex:
          expression: '(?P<timestamp>\d{2}:\d{2}:\d{2},\d{3}) \|-\s*(?P<level>[A-Z]+)'
      - timestamp:
          source: timestamp
          format: '15:04:05,000'
          location: Local
      - labels:
          filename:
          component:
          level:
