# Review Producer Application Configuration

# JVM timezone configuration for UTC
# Note: This should also be set via -Duser.timezone=UTC when starting the application
server:
  port: 7072

spring:
  application:
    name: review-producer
  
  datasource:
    url: jdbc:postgresql://localhost:5432/reviews
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          time_zone: UTC
    timezone: UTC
  
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all
      retries: 3
      batch-size: 16384
      linger-ms: 1
      buffer-memory: 33554432
    consumer:
      group-id: review-producer
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

# Kafka topic configuration
kafka:
  topic:
    reviews: good_review_records
    bad-reviews: bad_review_records
    dlq: dlq
  
  # DLQ retention configuration
  dlq:
    retention:
      ms: 604800000      # 7 days in milliseconds
      bytes: 1073741824  # 1GB in bytes
    segment:
      ms: 86400000       # 1 day segment rotation

# Enhanced Logging configuration
logging:
  level:
    root: INFO
    com.reviewproducer: DEBUG
    com.reviewcore: DEBUG
    org.springframework.kafka: INFO
    org.apache.kafka: WARN
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  
  file:
    name: /logs/review-producer.log
    max-size: 10MB
    max-history: 30
  
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 30
      total-size-cap: 1GB

# Actuator configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true

# Review Producer Configuration
review:
  producer:
    thread:
      pool:
        size: 2  # Number of processing threads
    queue:
      capacity: 100  # Maximum number of files in processing queue
    schedule:
      interval: 300000  # 5 minutes in milliseconds

# Vault Configuration
vault:
  host: localhost
  port: 8200
  token: devroot
  scheme: http
  #secret-path: /v1/secret/data/aes-key
  secret-path: secret/data/aes-key