spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/reviews
    username: postgres
    password: postgres

  redis:
    host: redis
    port: 6379
    timeout: 2000ms
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: -1ms
    connect-timeout: 5000ms
    socket-timeout: 3000ms

  kafka:
    bootstrap-servers: kafka:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

# Kafka topic configuration
kafka:
  topic:
    reviews: good_review_records
    bad-reviews: bad_review_records
    dlq: dlq
  
  # DLQ retention configuration
  dlq:
    retention:
      ms: 604800000      # 7 days in milliseconds
      bytes: 1073741824  # 1GB in bytes
    segment:
      ms: 86400000       # 1 day segment rotation
