global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'review-service-local'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['localhost:7070']

  - job_name: 'review-dashboard-local'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['localhost:8081']

  - job_name: 'review-producer-local'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['localhost:7072']

  - job_name: 'review-consumer-local'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['localhost:7073'] 