{
 "title": "Review Metrics Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Producer Invalid Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "review_producer_lines_processed_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Consumer File Processed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "review_consumer_processed_reviews_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Producer Processed Records",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "review_producer_files_found_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bad Error Records",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "review_consumer_bad_reviews_total",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}