server:
  port: 7073

spring:
  application:
    name: review-consumer
  
  datasource:
    url: jdbc:postgresql://localhost:5432/reviews
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    packages-to-scan: com.reviewcore.model, com.reviewconsumer.repository
  
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: review-consumer-group
      auto-offset-reset: earliest
      enable-auto-commit: false
      threads: 2

# Kafka topic configuration
kafka:
  topic:
    reviews: good_review_records
    bad-reviews: bad_review_records

logging:
  level:
    com.reviewconsumer: DEBUG
    org.springframework.kafka: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: /logs/review-consumer.log
    max-size: 10MB
    max-history: 30

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true 