spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/reviews
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  redis:
    host: localhost
    port: 6379
    timeout: 2000ms

kafka:
  bootstrap-servers: localhost:9092

sources:
  - name: agoda
    uri: minio://reviews/agoda/
    last-processed-timestamp: 0
  - name: booking
    uri: minio://reviews/booking/
    last-processed-timestamp: 0
  - name: expedia
    uri: minio://reviews/expedia/
    last-processed-timestamp: 0

fetcher:
  poll-interval-ms: 60000

flyway:
  enabled: true
  locations: classpath:db/migration

server:
  port: 7070

app:
  encryption:
    key: ${ENCRYPTION_KEY:defaultEncryptionKey12345678901234567890123456789012}

logging:
  level:
    root: ${LOG_LEVEL:INFO}
    com.reviewservice: ${REVIEW_SERVICE_LOG_LEVEL:DEBUG}
  file:
    name: ${LOG_FILE_PATH:./logs/review-service.log} 