name: Review System CI Build with JaCoCo

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build with Maven and Generate JaCoCo Reports
        # 'verify' phase typically triggers JaCoCo report generation if configured in parent POM
        run: mvn clean verify

      - name: Upload JaCoCo Code Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          # This path assumes JaCoCo aggregate report is configured in the parent POM
          # and generates to target/site/jacoco-aggregate/
          # Adjust the path if your JaCoCo configuration outputs to a different location
          path: |
            **/target/site/jacoco-aggregate/ 
            **/target/site/jacoco/
          # Path for the combined aggregate report
          # Path for individual module reports (each module's target/site/jacoco)
          # You might want to exclude .exec files if they're not needed
          # retention-days: 7 # Optional: how long to keep the artifact

      - name: Upload Surefire Test Reports (Optional but Recommended)
        uses: actions/upload-artifact@v4
        with:
          name: surefire-test-reports
          path: '**/surefire-reports/**/*.xml'